name: CI
on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
  workflow_dispatch:

jobs:
  cargo-build-and-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          persist-credentials: false
      - name: Install picotool
        run: |
          cd "$(mktemp -d)"
          git clone --single-branch --branch 2.1.1 --depth 1 https://github.com/raspberrypi/pico-sdk.git
          git -C pico-sdk submodule update --init --depth 1 lib/mbedtls
          git clone --single-branch --branch 2.1.1 --depth 1 https://github.com/raspberrypi/picotool.git
          cmake -S picotool -B build -D CMAKE_BUILD_TYPE=Release -D CMAKE_POLICY_VERSION_MINIMUM=3.5 -D PICOTOOL_NO_LIBUSB=ON -D PICO_SDK_PATH="$PWD/pico-sdk" -D CMAKE_INSTALL_PREFIX="$HOME/.local"
          cmake --build build
          cmake --install build
          picotool
      - name: Install flip-link
        run: cargo install --locked flip-link@0.1.10
      - run: "cargo test-libs --target \"$(rustc -vV | sed -n 's|host: ||p')\""
      - run: cargo build --release --bins --examples
      - run: picotool uf2 convert target/thumbv6m-none-eabi/release/gnss-7-seg-clock -t elf target/thumbv6m-none-eabi/release/gnss-7-seg-clock.uf2
      - uses: actions/upload-artifact@v4.6.2
        with:
          name: firmware
          path: |
            target/thumbv6m-none-eabi/release/gnss-7-seg-clock
            target/thumbv6m-none-eabi/release/gnss-7-seg-clock.uf2

  cargo-fmt:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4.2.2
      - run: cargo fmt --check

  cargo-clippy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4.2.2
      - run: cargo clippy -- -D warnings

  release-firmware:
    runs-on: ubuntu-24.04
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    needs:
      - cargo-build-and-test
    steps:
      - uses: actions/download-artifact@v5.0.0
        with:
          name: firmware
      - uses: softprops/action-gh-release@fbadcc90e88ecface60a0a0d123795b784ceb239
        with:
          draft: true
          files: |
            gnss-7-seg-clock
            gnss-7-seg-clock.uf2

  kicad:
    runs-on: ubuntu-24.04
    steps:
      - name: Run Schematic ERC
        uses: docker/bake-action@v6.8.0
        with:
          targets: erc
      - name: Export Schematic PDF
        uses: docker/bake-action@v6.8.0
        with:
          targets: pdf
      - name: Run PCB DRC
        uses: docker/bake-action@v6.8.0
        with:
          targets: drc

      - uses: actions/upload-artifact@v4.6.2
        continue-on-error: true
        with:
          name: kicad-outputs
          path: |
            out/*

      - name: Validate
        run: |
          {
            echo '### ERC'
            echo '```json'
            cat out/erc.json
            echo '```'
            echo '### DRC'
            echo '```json'
            cat out/drc.json
            echo '```';
          } >> "$GITHUB_STEP_SUMMARY"

          jq --exit-status '.sheets | map(.violations) | flatten(1) | length == 0' out/erc.json
          jq --exit-status '.violations | length == 0' out/drc.json
